pub mod admin;
pub mod bootstrap;
pub mod cli;
pub mod infra;
pub mod modules;
pub mod shared;
pub mod shutdown;
pub mod state;
pub mod ws;

// Plugin registration is currently handled by PluginLoader at runtime
// (see src/modules/plugin/loader.rs). Compile-time registration via
// build.rs is planned but not yet implemented.
//
// TODO: plugin_registry.rs should be generated by build.rs
// include!(concat!(env!("OUT_DIR"), "/plugin_registry.rs"));

#[cfg(test)]
pub mod tests;

use std::{net::SocketAddr, path::PathBuf, str::FromStr, sync::Arc, time::Duration};

use bootstrap::{config::AppConfig, router::build_router};
use sqlx::sqlite::{SqliteConnectOptions, SqliteJournalMode, SqlitePoolOptions};
use sqlx::ConnectOptions;
use state::AppState;
use tokio::sync::broadcast;

use crate::modules::plugin::manager::PluginManager;

pub async fn serve() -> anyhow::Result<()> {
    let config = AppConfig::load()?;
    config.validate()?;

    // 检测 Turnstile 配置不一致：secret 已配置但 site_key 为空
    if !config.auth.turnstile_secret.is_empty() && config.auth.turnstile_site_key.is_empty() {
        tracing::warn!(
            "Turnstile verification is configured (turnstile_secret is set) but turnstile_site_key is empty. \
             The Turnstile widget will not render on the login page, but backend validation is enabled. \
             This is likely a configuration error — set COLOPHON__AUTH__TURNSTILE_SITE_KEY to match."
        );
    }
    std::fs::create_dir_all(&config.storage.upload_dir)?;
    std::fs::create_dir_all(&config.theme.theme_dir)?;
    std::fs::create_dir_all(&config.storage.static_dir)?;

    let db_options = SqliteConnectOptions::from_str(&config.database.url)?
        .journal_mode(SqliteJournalMode::Wal) // WAL 模式
        .busy_timeout(Duration::from_secs(5)) // 写锁自旋等待 5s
        .pragma("synchronous", "NORMAL") // WAL 下安全 + 高性能
        .pragma("foreign_keys", "ON") // 外键约束
        .pragma("temp_store", "MEMORY") // 临时表放内存，加速 FTS5
        .pragma("mmap_size", "268435456") // 256MB 内存映射加速读
        .log_slow_statements(
            tracing_log::log::LevelFilter::Warn,
            Duration::from_millis(100),
        );

    let pool = SqlitePoolOptions::new()
        .max_connections(5)
        .connect_with(db_options)
        .await?;
    sqlx::migrate!("./migrations").run(&pool).await?;

    // 创建 WebSocket broadcast channel，容量 256
    let (event_tx, _rx) = broadcast::channel::<ws::ServerEvent>(256);

    let setup_runtime = modules::setup::service::bootstrap_runtime(&pool).await?;

    // Wave 3.2: 扫描 plugins/ 目录下的 .wasm 文件，编译为 Manifest 并注册 Hooks
    use crate::modules::plugin::loader::PluginLoader;

    let loader = PluginLoader::new(PathBuf::from("plugins"), env!("CARGO_PKG_VERSION"));
    let discovered = loader.discover(&pool).await?;
    let plugin_manager = Arc::new(tokio::sync::RwLock::new(
        PluginManager::load_with(discovered).await,
    ));
    tracing::info!(
        module = "plugin",
        discovered = plugin_manager.read().await.discovered_manifests().len(),
        "PluginManager initialized with Wasm runtime"
    );

    let state = Arc::new(AppState::new(
        config.clone(),
        pool,
        event_tx,
        setup_runtime.site_url,
        setup_runtime.admin_url,
        setup_runtime.stage,
        plugin_manager.clone(),
    )?);

    state.plugin_manager.write().await.init_all(&state).await?;
    // 初始化 Webhook 分发器，注册到全局 HookRegistry
    {
        let resolver = std::sync::Arc::new(modules::webhook::dns::TokioDnsResolver);
        let dispatcher = modules::webhook::dispatcher::WebhookDispatcher::new(
            state.pool.clone(),
            config.webhook.clone(),
            resolver,
        );
        let hooks = dispatcher.into_hooks();
        state
            .plugin_manager
            .read()
            .await
            .hook_registry()
            .register("webhook", hooks)
            .await;
    }
    modules::backup::scheduler::start_backup_scheduler(state.clone()).await?;
    modules::trash::scheduler::start_trash_scheduler(state.clone()).await?;

    // 启动定时发布调度器
    let post_scheduler_state = state.clone();
    let post_scheduler_cancel = state.shutdown_token.clone();
    tokio::spawn(async move {
        modules::post::scheduler::start_post_scheduler(post_scheduler_state, post_scheduler_cancel).await;
    });

    // ── 启动 WebP 转换 worker ──
    if state.config.media.webp_enabled {
        let (tx, handle) = modules::media::worker::start_webp_worker(
            state.pool.clone(),
            state.upload_dir.clone(),
            &state.config.media,
            state.shutdown_token.clone(),
        );
        state.converter_send.lock().await.replace(tx);

        tracing::info!(
            webp_enabled = true,
            max_edge = state.config.media.webp_max_edge,
            max_concurrent = state.config.media.webp_max_concurrent,
            "webp conversion worker started"
        );

        // 启动时扫描 pending 状态的旧记录，重新入队
        match modules::media::repository::list_pending_conversions(&state.pool).await {
            Ok(pending) => {
                if !pending.is_empty() {
                    tracing::info!(
                        count = pending.len(),
                        "found pending conversions, re-enqueuing"
                    );
                    for item in pending {
                        let sender_guard = state.converter_send.lock().await;
                        if let Some(ref tx) = *sender_guard {
                            let job = modules::media::worker::ConversionJob {
                                media_id: item.id.clone(),
                                source_path: state.upload_dir.join(&item.storage_path),
                                mime_type: item.mime_type.clone(),
                                file_size: item.size_bytes as u64,
                            };
                            let _ = tx.try_send(job);
                        }
                    }
                }
            }
            Err(e) => {
                tracing::warn!(error = %e, "failed to list pending conversions on startup");
            }
        }

        // 存入 state 供 shutdown 使用
        state.webp_worker_handle.lock().await.replace(handle);
    }

    // 启动主题文件监听器（仅开发模式）。
    // 失败不阻止服务启动 —— 退化为"修改后手动重启"模式即可。
    if let Err(e) = infra::file_watcher::spawn_theme_watcher(state.clone(), &state.theme_dir).await
    {
        tracing::warn!(error = ?e, "failed to start theme file watcher; continuing without hot-reload");
    }

    let app = build_router(state.clone()).await;

    let addr = SocketAddr::new(config.server.host.parse()?, config.server.port);
    tracing::info!("Colophon listening on http://{}", addr);

    let listener = tokio::net::TcpListener::bind(addr).await?;

    // ── 优雅关闭 ──
    // 用 oneshot channel 桥接信号监听和 axum graceful shutdown
    let (shutdown_tx, shutdown_rx) = tokio::sync::oneshot::channel::<()>();

    // axum serve 放在 tokio task 中以获取 JoinHandle 实现超时控制
    let serve_task = tokio::spawn(async move {
        axum::serve(
            listener,
            app.into_make_service_with_connect_info::<SocketAddr>(),
        )
        .with_graceful_shutdown(async {
            let _ = shutdown_rx.await;
        })
        .await
    });

    // 等待 OS 信号
    crate::shutdown::wait_for_shutdown_signal().await;

    // 通知 axum 停止接受新连接，开始 drain
    let _ = shutdown_tx.send(());
    tracing::info!("notified axum to stop accepting new connections");

    // 等待 axum drain 完成，超过配置的超时则强制退出
    let drain_timeout = Duration::from_secs(state.config.server.graceful_shutdown_timeout_seconds);
    let abort_handle = serve_task.abort_handle();
    tokio::select! {
        result = serve_task => {
            // result 的类型是 Result<Result<(), anyhow::Error>, JoinError>
            // 外层 Result 来自 tokio::spawn 的 JoinHandle（task 是否 panic）
            // 内层 Result 来自 axum::serve 的返回值（服务是否正常退出）
            match result {
                // JoinHandle 正常 + axum 正常 drain 退出
                Ok(Ok(())) => tracing::info!("axum server drained gracefully"),
                // JoinHandle 正常 + axum 返回错误（如绑定失败）
                Ok(Err(e)) => tracing::error!(error = %e, "axum server exited with error"),
                // tokio::spawn 的 task panic 了（JoinError）
                Err(join_err) => tracing::error!(error = %join_err, "axum serve task panicked"),
            }
        }
        _ = tokio::time::sleep(drain_timeout) => {
            tracing::warn!(
                timeout_secs = drain_timeout.as_secs(),
                "graceful shutdown drain timeout reached, forcing exit"
            );
            abort_handle.abort();
        }
    }

    // 执行清理序列
    crate::shutdown::run_shutdown_sequence(&state).await;

    Ok(())
}
